# Generated by Django 3.1 on 2020-08-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_product_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_image',
            field=models.ImageField(default='default.png', upload_to='post_images'),
        ),
    ]
